import {
  IAggregateGroupBy,
  IAggregateMeta,
  IAggregateNumber,
  IAggregateReference,
  IAggregateString,
} from './fields'
import { IAggregateBoolean } from './fields/common/AggregateBoolean.interface'

export interface IAggregateSubtitleFile {
  media: IAggregateReference
  originalName: IAggregateString
  mimeType: IAggregateString
  language: IAggregateString
  entries: IAggregateReference
  autogenerated: IAggregateBoolean
  size: IAggregateNumber
  url: IAggregateString
  path: IAggregateString
  pathString: IAggregateString
  sourceId: IAggregateString
  remoteId: IAggregateString

  groupedBy: IAggregateGroupBy
  meta: IAggregateMeta
}
